# Generated by Django 5.0.6 on 2024-06-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0005_room_player1_move_room_player2_move_room_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1_move',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2_move',
        ),
        migrations.RemoveField(
            model_name='room',
            name='result',
        ),
    ]
