# Generated by Django 5.0.6 on 2024-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0006_remove_room_player1_move_remove_room_player2_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player1_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
