# Generated by Django 5.0.6 on 2024-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0007_room_player1_room_player1_move_room_player2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1_move',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2_move',
        ),
        migrations.AddField(
            model_name='room',
            name='player1_moves',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_moves',
            field=models.JSONField(default=list),
        ),
    ]
