# Generated by Django 5.0.6 on 2024-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0008_remove_room_player1_move_remove_room_player2_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1_moves',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2_moves',
        ),
        migrations.RemoveField(
            model_name='room',
            name='result',
        ),
        migrations.AddField(
            model_name='room',
            name='final_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player1_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_move',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='result1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='result2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='result3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
