# Generated by Django 5.0.6 on 2024-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0009_remove_room_player1_moves_remove_room_player2_moves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='result3',
        ),
        migrations.AddField(
            model_name='room',
            name='player1_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_wins',
            field=models.IntegerField(default=0),
        ),
    ]
